# Generated by Django 2.1.7 on 2019-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('remider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTriggerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
